name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-dev build-essential \
            libssl-dev libffi-dev libncurses5-dev libsqlite3-dev zlib1g-dev \
            openjdk-11-jdk

      - name: Install Python packages
        run: |
          pip install --upgrade pip setuptools wheel      # setuptools provides distutils :contentReference[oaicite:4]{index=4}
          pip install cython                               # needed by python-for-android 
          pip install buildozer                            # installs latest 1.5.0 :contentReference[oaicite:5]{index=5}

      - name: Build APK using Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4                # only v4 is supported now :contentReference[oaicite:6]{index=6}
        with:
          name: apk
          path: ./.buildozer/android/platform/build-dists/*/bin/*.apk


