name: Build Kivy Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            build-tools;33.0.2
            platform-tools
            platforms;android-33

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip git \
            python3-pip openjdk-17-jdk \
            libffi-dev libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 \
            libtool pkg-config autoconf cmake \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython setuptools buildozer

      - name: Build Android APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk



