name: Build Kivy APK

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-dev build-essential \
            libssl-dev libffi-dev libncurses5-dev libsqlite3-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip setuptools
          pip install cython
          pip install buildozer

      - name: Build APK using Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./.buildozer/android/platform/build/dists/*/bin/*.apk


