name: Build Kivy APK
on:
  push:
    branches:
        main
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
        name: checkout code
        uses: actions/checkout@v4
        name: Set up Python
        uses: actiona/setup-python@v4
        with:
          python-version: '3.x'
        name: Install Buildozer and dependencies
        run:
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools libnucurses5-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer
        name: Build APK using Buildozer
        run:  |
          buildozer -v android debug
        name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: /buildozer/android/platform/build/dists/*/bin/*.apk
