name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-dev build-essential \
            libssl-dev libffi-dev libncurses5-dev libsqlite3-dev zlib1g-dev \
            openjdk-11-jdk unzip wget

      - name: Download Android command line tools
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          cd "$HOME/android-sdk/cmdline-tools"
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.0.0"

      - name: Install Python packages
        run: |
          pip install --upgrade pip setuptools wheel
          pip install cython
          pip install buildozer==1.5.0

      - name: Build APK using Buildozer
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer -v android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./.buildozer/android/platform/build-dists/*/bin/*.apk



